CREATE CACHED TABLE "PUBLIC"."DEPARTMENT"(

    "DEPT_CODE" CHARACTER VARYING(255) NOT NULL,

    "DEPT_LEVEL" INTEGER,

    "DEPT_NAME" CHARACTER VARYING(255),

    "DEPT_NAME_EN" CHARACTER VARYING(255),

    "HEAD_EMP_NO" BIGINT,

    "UPPER_DEPT_CODE" CHARACTER VARYING(255)

);