CREATE CACHED TABLE "PUBLIC"."POSITION"(

    "POSITION_CODE" CHARACTER VARYING(255) NOT NULL,

    "POSITION_LEVEL" INTEGER,

    "POSITION_NAME" CHARACTER VARYING(255),

    "POSITION_NAME_EN" CHARACTER VARYING(255)

);